CREATE TABLE /*TABLE_PREFIX*/t_feature_banner (
    i_banner_id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    s_path VARCHAR(255),
    s_name VARCHAR(255),
    s_link VARCHAR(600)

) ENGINE=InnoDB DEFAULT CHARACTER SET 'UTF8' COLLATE 'UTF8_GENERAL_CI';
